name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS (if needed)
        run: |
          git lfs install

      - name: Configure Git with your Hugging Face Token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://nucmedsolutions:$HF_TOKEN@huggingface.co/spaces/nucmedsolutions/Search_Engine_LLM.git

      - name: Pull from remote before pushing
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull origin main --rebase

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push origin main

